# Generated by Django 5.2.15 on 2026-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Whitelist user',
                'verbose_name_plural': 'Whitelist users',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('model_used', models.CharField(default='llama-4-scout-17b-16e-instruct', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='screener.screenshot')),
            ],
            options={
                'verbose_name': 'Analysis result',
                'verbose_name_plural': 'Analysis results',
                'ordering': ['-created_at'],
            },
        ),
    ]
